# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: konradbartecki@outlook.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/"
url: "http://konradbartecki.github.io"
twitter_username: KBartecki
github_username:  konradbartecki
facebook_username:  none

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
