# Site settings
title: "Konrad Bartecki"
email: konradbartecki@outlook.com
description: "Konrad Bartecki - personal blog"
baseurl: ""
url: "http://bartecki.pro"
title_description: "Microsoft Certified Professional, .NET Developer at Predica.pl"
title_image: "http://www.gravatar.com/avatar/786789f1086629a378382f3b3121dcf1.jpg?s=500&d=mm"
#google_analytics: "UA-20365477-4"
disqus_account: barteckipro
github_repository: https://github.com/konradbartecki/konradbartecki.github.io
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: KBartecki
github_username:  konradbartecki
linkedin_link: http://linkedin.com/in/konradbartecki
windows_store_link: https://www.microsoft.com/en-us/search/result.aspx?q=Konrad+Bartecki&form=apps
stackoverflow_link: http://stackoverflow.com/users/3880556/konrad-bartecki

# Footer
theme_attribution: "Get this theme on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"
ms_trademark: "<p style=\"font-size:small\">Microsoft is a registered trademark of Microsoft Corporation in the United States and other countries.</p>"


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
