# Site settings
title: "Konrad Bartecki"
email: konradbartecki@outlook.com
description: "Konrad Bartecki - personal blog"
baseurl: ""
url: "http://bartecki.pro/"
title_description: "Mobile, Windows Phone, C# and Xamarin developer living in Warsaw, Poland"
title_image: "http://www.gravatar.com/avatar/786789f1086629a378382f3b3121dcf1.jpg?s=500&d=mm"
#google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
#github_repository: https://github.com/jacobtomlinson/carte-noire
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: KBartecki
github_username:  konradbartecki
linkedin_link: http://linkedin.com/in/konradbartecki
windows_store_link: https://www.microsoft.com/en-us/search/result.aspx?q=Konrad+Bartecki&form=apps
stackoverflow_link: http://stackoverflow.com/users/3880556/konrad-bartecki

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
